categories = ["Added", "Changed", "Fixed", "Improved", "Removed", "Feat", "Doc", "Perf", "Refact", "Style", "Test", "Chore"]
category_delimiters = ["[", "]"]
colored_output = true
enable_debug = true
excluded_commit_tags = []
enable_footers = true
show_commit_hash = true
show_prefix = true
sort_by = "date"
template_prefix = "DTIG Change Log"
